version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  server:
    build: ./server
    entrypoint: yarn start dev
    ports:
      - "5000:5000"
  robot:
    build: ./robot
